// <auto-generated />
namespace TravelTripProje.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class yorum_notnull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(yorum_notnull));
        
        string IMigrationMetadata.Id
        {
            get { return "202311272036454_yorum_notnull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
